platform = "linux"
dest = "/home/oyzh/Package/EasyShell/${appVersion}/"
appIcon = "${projectPath}/resource/app.png"
#appImageRuntime = "${pkgPath}/AppImage"

[jpackage]
#java-options = [
#    "-XX:+UseZGC",
#    "-XX:ZUncommitDelay=1"
#]
type = "app-image"

[jar]
excludes = [
    ".*.dll",
    ".*.dylib",
    ".*com/pty4j/native/darwin.*",
    ".*com/pty4j/native/win.*",
    ".*com/sun/jna/darwin.*",
    ".*com/sun/jna/win32.*"
]
