platform = "macos"
dest = "/Users/oyzh/Desktop/Package/EasyShell/${appVersion}/"
appIcon = "${projectPath}/resource/app.icns"

[jpackage]
#java-options = [
#    "-XX:+UseG1GC"
#]
type = "dmg"
mac-package-identifier = "cn.oyzh.easyshell"

[jar]
excludes = [
    ".*.dll",
    ".*.so",
    ".*com/pty4j/native/freebsd.*",
    ".*com/pty4j/native/linux.*",
    ".*com/pty4j/native/win.*",
    ".*com/sun/jna/linux.*",
    ".*com/sun/jna/win32.*"
]
