platform = "windows"
appIcon = "${projectPath}/resource/app.ico"
dest = "C:/Package/EasyShell/${appVersion}/EasyShell"

[jpackage]
java-options = [
#    "-XX:+UseZGC",
#    "-XX:ZUncommitDelay=1",
    "-Dprism.forceUploadingPainter=true",
    "-Dquantum.multithreaded=false"
]
type = "app-image"

[compress]
type = "zip"

[jar]
excludes = [
    ".*.dylib",
    ".*.so",
    ".*com/pty4j/native/freebsd.*",
    ".*com/pty4j/native/linux.*",
    ".*com/pty4j/native/darwin.*",
    ".*com/pty4j/native/win/x86/.*",
    ".*com/pty4j/native/win/aarch64/.*",
    ".*com/sun/jna/linux.*",
    ".*com/sun/jna/darwin.*",
    ".*com/sun/jna/win32-x86/.*",
    ".*com/sun/jna/win32-aarch64/.*",
    "ucrtbase.dll",
    "api-ms-.*.dll",
    "msvcp140.*.dll",
    "vcruntime140.*.dll"
]
